In [28]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [29]:
orders = pd.read_csv('clean_orders.csv')
orders.head()

,customer_id,order_id,product_code,product_name,quantity,unit_price,purchase_date,line_total,is_subproduct
0,T24540,TS010135579,362,Clinique For Men Kırışık Karşıtı Göz Kremi 15 Ml,1,756.0,2024-01-01,756.0,False
1,T24667,TS010135506,1212,Lancome Hypnose Kadın Parfüm Edp 75 Ml,1,2990.0,2024-01-01,2990.0,False
2,T24668,TS010135510,1970,Carolina Herrera 212 Sexy Men Erkek Parfüm Edt...,1,2449.6,2024-01-01,2449.6,False
3,ts_1704131707_8429,TS010135585,1970,Carolina Herrera 212 Sexy Men Erkek Parfüm Edt...,1,2449.6,2024-01-01,2449.6,False
4,T1186,TS010135548,3480,YSL La Nuit De L'Homme Erkek Deo Stick 75 Gr,1,916.5,2024-01-01,916.5,False

In [30]:
basket = (
    orders
    .groupby(['order_id', 'product_name'])['quantity']
    .sum()
    .unstack()
    .fillna(0)
)

In [31]:
basket = basket.applymap(lambda x: 1 if x > 0 else 0).astype(bool)

C:\Users\alber\AppData\Local\Temp\ipykernel_56800\1420795208.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  basket = basket.applymap(lambda x: 1 if x > 0 else 0).astype(bool)

In [32]:
basket.head()

product_name,Active Nature Ağda Bezi 10 Mt,Active Nature Boncuk Ağda Naturel 250 Gr,Active Nature Roll-On Kartuş Ağda Pudralı 100 Gr,Alix Kit Saç Boyası 1.1 Mavi Siyah,Alix Kit Saç Boyası 10.0 Açık Sarı,Alix Kit Saç Boyası 3.0 Koyu Kahve,Alix Kit Saç Boyası 4.0 Kahve,Alix Kit Saç Boyası 4.6 Ateş Kızılı,Alix Kit Saç Boyası 5.35 Işıltılı Kahve,Alix Kit Saç Boyası 5.8 Büyüleyici Kahve,...,İpek Pamuk 100 Gr,İpek Renkli Makyaj Temizleme Pamuğu 50'li Pompon,Şef Stick Lip Care Kakao Spf15,Şef Stick Lip Care Kivi,Şef Stick Lip Care Men Natural Erkek Spf15,Şef Stick Lip Care UV5 Natural Spf15,Şelale Aseton Besleyici 120 Ml,Şelale Aseton Besleyici 180 Ml,Şelale Aseton Besleyici 50 Ml,Şelale Asetonsuz Oje Temizleyici 120 Ml
order_id,,,,,,,,,,,,,,,,,,,,,
TS0101124628,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124633,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124634,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124635,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124636,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [33]:
basket.describe()

product_name,Active Nature Ağda Bezi 10 Mt,Active Nature Boncuk Ağda Naturel 250 Gr,Active Nature Roll-On Kartuş Ağda Pudralı 100 Gr,Alix Kit Saç Boyası 1.1 Mavi Siyah,Alix Kit Saç Boyası 10.0 Açık Sarı,Alix Kit Saç Boyası 3.0 Koyu Kahve,Alix Kit Saç Boyası 4.0 Kahve,Alix Kit Saç Boyası 4.6 Ateş Kızılı,Alix Kit Saç Boyası 5.35 Işıltılı Kahve,Alix Kit Saç Boyası 5.8 Büyüleyici Kahve,...,İpek Pamuk 100 Gr,İpek Renkli Makyaj Temizleme Pamuğu 50'li Pompon,Şef Stick Lip Care Kakao Spf15,Şef Stick Lip Care Kivi,Şef Stick Lip Care Men Natural Erkek Spf15,Şef Stick Lip Care UV5 Natural Spf15,Şelale Aseton Besleyici 120 Ml,Şelale Aseton Besleyici 180 Ml,Şelale Aseton Besleyici 50 Ml,Şelale Asetonsuz Oje Temizleyici 120 Ml
count,53435,53435,53435,53435,53435,53435,53435,53435,53435,53435,...,53435,53435,53435,53435,53435,53435,53435,53435,53435,53435
unique,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
freq,53428,53434,53433,53432,53434,53433,53431,53434,53433,53431,...,53412,53429,53426,53432,53422,53428,53432,53409,53432,53433

In [46]:
from mlxtend.frequent_patterns import apriori, association_rules

min_support = 20 / basket.shape[0]
frequent_itemsets = apriori(basket,
                            min_support=min_support,
                            use_colnames=True,
                            low_memory=True)

rules = association_rules(frequent_itemsets,
                          metric="confidence",
                          min_threshold=0.01)

In [47]:
rules[['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
0,(Arko Coffee Traş Jeli 200 Ml),(Arko Black Traş Jeli 200 Ml),0.000468,0.781250,907.523777
1,(Arko Black Traş Jeli 200 Ml),(Arko Coffee Traş Jeli 200 Ml),0.000468,0.543478,907.523777
2,(Arko Men Anti Irritation Tıraş Jeli 200 Ml),(Arko Black Traş Jeli 200 Ml),0.000449,0.480000,557.582609
3,(Arko Black Traş Jeli 200 Ml),(Arko Men Anti Irritation Tıraş Jeli 200 Ml),0.000449,0.521739,557.582609
4,(Arko Men Sensitive Tıraş Jeli 200 Ml),(Arko Black Traş Jeli 200 Ml),0.000524,0.583333,677.617754
...,...,...,...,...,...
375,(Arko Nem Extra Nemlendirici Krem 250 Ml + 250...,"(Arko Nem Avokado Krem 250 Ml + 250 Ml Set, Ar...",0.000374,0.444444,659.691358
376,(Arko Nem Avokado Krem 250 Ml + 250 Ml Set),"(Arko Nem Soft Touch Krem 250 Ml + 250 Ml Set,...",0.000374,0.235294,392.904412
377,(Arko Nem Soft Touch Krem 250 Ml + 250 Ml Set),"(Arko Nem Avokado Krem 250 Ml + 250 Ml Set, Ar...",0.000374,0.151515,279.179728
378,(Arko Nem Extra Nemlendirici Krem 250 Ml + 250...,"(Arko Nem Avokado Krem 250 Ml + 250 Ml Set, Ar...",0.000374,0.147059,291.040305
379,(Arko Nem Prebiyotik Badem Krem 250 Ml + 250 M...,"(Arko Nem Avokado Krem 250 Ml + 250 Ml Set, Ar...",0.000374,0.227273,467.089161

In [48]:
rules.to_csv('association_rules.csv', index=False)

In [49]:
basket.shape

(53435, 11169)

In [53]:
# 1) Clean: turn frozensets into single-item strings (works for 1→1 rules)
rules_clean = rules.copy()
rules_clean = rules_clean[rules_clean['antecedents'].apply(len) == 1]
rules_clean = rules_clean[rules_clean['consequents'].apply(len) == 1]

rules_clean['product'] = rules_clean['antecedents'].apply(lambda s: next(iter(s)))
rules_clean['complement'] = rules_clean['consequents'].apply(lambda s: next(iter(s)))

# 2) Optional: keep only positive association
rules_clean = rules_clean[rules_clean['lift'] > 1].copy()

# 3) Create rank (THIS is the missing step in your notebook state)
rules_clean = rules_clean.sort_values(['product', 'lift', 'confidence', 'support'],
                                      ascending=[True, False, False, False])

rules_clean['rank'] = rules_clean.groupby('product').cumcount() + 1

# 4) Top 5
top3 = rules_clean[rules_clean['rank'] <= 3].copy()

top3_table = top3[['product', 'complement', 'lift', 'confidence', 'support', 'rank']] \
    .sort_values(['product', 'rank'])

top3_table.head(20)

,product,complement,lift,confidence,support,rank
1,Arko Black Traş Jeli 200 Ml,Arko Coffee Traş Jeli 200 Ml,907.523777,0.543478,0.000468,1
5,Arko Black Traş Jeli 200 Ml,Arko Men Sensitive Tıraş Jeli 200 Ml,677.617754,0.608696,0.000524,2
3,Arko Black Traş Jeli 200 Ml,Arko Men Anti Irritation Tıraş Jeli 200 Ml,557.582609,0.521739,0.000449,3
0,Arko Coffee Traş Jeli 200 Ml,Arko Black Traş Jeli 200 Ml,907.523777,0.781250,0.000468,1
7,Arko Cool Traş Jeli 200 Ml,Arko Men Sensitive Tıraş Jeli 200 Ml,420.086478,0.377358,0.000374,1
9,Arko Men Anti Irritation Tıraş Jeli 200 Ml,Arko Men Sensitive Tıraş Jeli 200 Ml,601.143750,0.540000,0.000505,1
2,Arko Men Anti Irritation Tıraş Jeli 200 Ml,Arko Black Traş Jeli 200 Ml,557.582609,0.480000,0.000449,2
4,Arko Men Sensitive Tıraş Jeli 200 Ml,Arko Black Traş Jeli 200 Ml,677.617754,0.583333,0.000524,1
8,Arko Men Sensitive Tıraş Jeli 200 Ml,Arko Men Anti Irritation Tıraş Jeli 200 Ml,601.143750,0.562500,0.000505,2
6,Arko Men Sensitive Tıraş Jeli 200 Ml,Arko Cool Traş Jeli 200 Ml,420.086478,0.416667,0.000374,3
15,Arko Nem Aloe Vera Nemlendirici Bakım Kremi 30...,Arko Nem Hindistan Cevizi Yağı Nemlendirici Ba...,303.991783,0.477876,0.001011,1
16,Arko Nem Aloe Vera Nemlendirici Bakım Kremi 30...,Arko Nem Prebiyotik Badem Krem 250 Ml + 250 Ml...,134.339803,0.221239,0.000468,2
11,Arko Nem Aloe Vera Nemlendirici Bakım Kremi 30...,Arko Nem Avokado Krem 250 Ml + 250 Ml Set,127.954711,0.203540,0.000430,3
22,Arko Nem Avokado Krem 250 Ml + 250 Ml Set,Arko Nem Prebiyotik Badem Krem 250 Ml + 250 Ml...,278.604947,0.458824,0.000730,1
20,Arko Nem Avokado Krem 250 Ml + 250 Ml Set,Arko Nem Extra Nemlendirici Krem 250 Ml + 250 ...,180.273789,0.458824,0.000730,2
24,Arko Nem Avokado Krem 250 Ml + 250 Ml Set,Arko Nem Soft Touch Krem 250 Ml + 250 Ml Set,171.449198,0.423529,0.000674,3
26,Arko Nem Extra Nemlendirici Krem 250 Ml + 250 ...,Arko Nem Prebiyotik Badem Krem 250 Ml + 250 Ml...,200.917029,0.330882,0.000842,1
21,Arko Nem Extra Nemlendirici Krem 250 Ml + 250 ...,Arko Nem Avokado Krem 250 Ml + 250 Ml Set,180.273789,0.286765,0.000730,2
29,Arko Nem Extra Nemlendirici Krem 250 Ml + 250 ...,Arko Nem Soft Touch Krem 250 Ml + 250 Ml Set,175.616366,0.433824,0.001104,3
14,Arko Nem Hindistan Cevizi Yağı Nemlendirici Ba...,Arko Nem Aloe Vera Nemlendirici Bakım Kremi 30...,303.991783,0.642857,0.001011,1

In [54]:
top3_table.to_csv("product_top3_complements.csv", index=False)

We still face the problem of cold start with new products or ones that haven't been bought enough yet. Will now try to use the product info to identify if types of products are more commonly complements, instead of checking for each product.

In [55]:
products = pd.read_csv('clean_products.csv')
products.head()

,product_name,product_code,category_main,category_mid,category_sub,full_path,price_original,price_discounted,brand,discount_pct,price_anomaly,ever_purchased
0,Sesu Sir Ağda Bantları Normal Tüyler 12'li,24568,Kişisel Bakım,Epilasyon Ürünleri,Ağda Bantları,Kişisel Bakım > Epilasyon Ürünleri > Ağda Bant...,0.0,0.0,Sesu,0.0,False,False
1,Sesu Vücut Ağda Bandı Kalın Tüy 12'li,24569,Kişisel Bakım,Epilasyon Ürünleri,Ağda Bantları,Kişisel Bakım > Epilasyon Ürünleri > Ağda Bant...,0.0,0.0,Sesu,0.0,False,False
2,YSL La Vestiaire Universite Unisex Parfüm Edp ...,117829,Parfüm,Unisex Parfüm,EDP Parfüm,Parfüm > Unisex Parfüm >EDP Parfüm,0.0,0.0,YSL,0.0,False,False
3,Pastel Show By Eyeliner 124,1458-907,Makyaj,Göz,Eyeliner,Makyaj > Göz > Eyeliner,0.0,0.0,Pastel,0.0,False,False
4,L'Oréal Paris Infaillible 24H Matte Cover Foun...,1135-1044,Makyaj,Yüz,Fondöten,Makyaj > Yüz > Fondöten,0.0,0.0,Loreal Paris Makyaj,0.0,False,True

In [59]:
products_unique = products[['product_name','category_sub', 'brand']].drop_duplicates()
orders2 = orders.merge(
    products_unique,
    left_on='product_name',
    right_on='product_name',
    how='left'
)
orders2.head()

,customer_id,order_id,product_code,product_name,quantity,unit_price,purchase_date,line_total,is_subproduct,category_sub,brand
0,T24540,TS010135579,362,Clinique For Men Kırışık Karşıtı Göz Kremi 15 Ml,1,756.0,2024-01-01,756.0,False,Göz & Dudak Bakım,Clinique
1,T24667,TS010135506,1212,Lancome Hypnose Kadın Parfüm Edp 75 Ml,1,2990.0,2024-01-01,2990.0,False,EDP Parfüm,Lancome
2,T24668,TS010135510,1970,Carolina Herrera 212 Sexy Men Erkek Parfüm Edt...,1,2449.6,2024-01-01,2449.6,False,EDT Parfüm,Carolina Herrera
3,ts_1704131707_8429,TS010135585,1970,Carolina Herrera 212 Sexy Men Erkek Parfüm Edt...,1,2449.6,2024-01-01,2449.6,False,EDT Parfüm,Carolina Herrera
4,T1186,TS010135548,3480,YSL La Nuit De L'Homme Erkek Deo Stick 75 Gr,1,916.5,2024-01-01,916.5,False,Deo Stick,YSL

In [60]:
orders.shape

(102885, 9)

In [61]:
orders2.shape

(102896, 11)

In [65]:
products.groupby('product_name')['category_sub'].nunique().sort_values(ascending=False).head(10)

product_name
Dior Capture Care Creme Jar 50 Ml                   2
Vaseline Nemlendirici Jel Baby 100 Ml               2
Vaseline Nemlendirici Jel Cocoa Butter 100 Ml       2
Vaseline Nemlendirici Jel Original 100 Ml           2
Alix Saç Boyası 1.0 Siyah                           1
Çift Kaplan 890 Korse Külot Ribana Beyaz            1
Alix Saç Boyası 6.11 Koyu Kumral Yoğun Küllü        1
Şef Stick Kids Lip Balm Barbie Kids 4.8 Gr          1
İpek Kulak Temizleme Pamuğu 300'lü Yuvarlak Kutu    1
Alix Saç Boyası 3.0 Koyu Kestane                    1
Name: category_sub, dtype: int64

In [67]:
conflicts = (
    products
    .groupby('product_name')
    .filter(lambda x: x['category_sub'].nunique() > 1)
)

In [69]:
conflict_summary = (
    conflicts
    .groupby('product_name')
    .agg({
        'brand': lambda x: x.dropna().unique().tolist(),
        'category_sub': lambda x: x.dropna().unique().tolist()
    })
    .reset_index()
)

In [70]:
conflict_summary

,product_name,brand,category_sub
0,Dior Capture Care Creme Jar 50 Ml,[Dior],"[Gece Kremi, Gündüz Kremi]"
1,Vaseline Nemlendirici Jel Baby 100 Ml,[Vaseline],"[Nemlendirici Krem, Nemlendirici]"
2,Vaseline Nemlendirici Jel Cocoa Butter 100 Ml,[Vaseline],"[Nemlendirici Krem, El Bakım]"
3,Vaseline Nemlendirici Jel Original 100 Ml,[Vaseline],"[Nemlendirici Krem, El Bakım]"

In [71]:
basket_category = (
    orders2
    .groupby(['order_id', 'category_sub'])['quantity']
    .sum()
    .unstack()
    .fillna(0)
)
basket_category = basket_category.map(lambda x: 1 if x > 0 else 0).astype(bool)

basket_brand = (
    orders2
    .groupby(['order_id', 'brand'])['quantity']
    .sum()
    .unstack()
    .fillna(0)
)
basket_brand = basket_brand.map(lambda x: 1 if x > 0 else 0).astype(bool)

In [73]:
basket_category.head()

category_sub,After Shave Balsam,After Shave Losyon,Akne Bakım,Allık,Aseton,Atlet,Ayak Bakım,Aydınlatıcı,Ağda Bantları,Ağda Malzemeleri,...,Tıraş Makinesi,Tırnak Bakım,Vücut Losyonu,Vücut Yağı,Vücut Şampuanı,Wax,Yedek Tıraş Bıçakları,Çorap,Şampuan,Şort
order_id,,,,,,,,,,,,,,,,,,,,,
TS0101124628,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124633,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124634,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124635,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124636,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [74]:
basket_brand.head()

brand,Active,Alix Boya,Alix Kit,Altan,Amarsi,Amouroud,Anagen,Anthology,Antonio Banderas,Areon,...,Welton,Xo,YSL,Yeni İnci,Yıkamaks,Zadig&Voltaire,Zigavus,Çift Kaplan,Şef Stick,Şelale
order_id,,,,,,,,,,,,,,,,,,,,,
TS0101124628,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
TS0101124633,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124634,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
TS0101124635,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
TS0101124636,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [75]:
min_support = 20 / basket.shape[0]
frequent_itemsets2 = apriori(basket_category,
                            min_support=min_support,
                            use_colnames=True,
                            low_memory=True)

rules_category = association_rules(frequent_itemsets2,
                          metric="confidence",
                          min_threshold=0.01)

min_support = 20 / basket.shape[0]
frequent_itemsets3 = apriori(basket_brand,
                            min_support=min_support,
                            use_colnames=True,
                            low_memory=True)

rules_brand = association_rules(frequent_itemsets3,
                          metric="confidence",
                          min_threshold=0.01)

In [76]:
rules_category[['antecedents','consequents','support','confidence','lift']]
rules_brand[['antecedents','consequents','support','confidence','lift']]
rules_category.to_csv('association_rules_category.csv', index=False)
rules_brand.to_csv('association_rules_brand.csv', index=False)

In [77]:
rules_category

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(After Shave Losyon),(Roll-On),0.003981,0.028689,0.000410,0.102941,3.588165,1.0,0.000296,1.082773,0.724189,0.012704,0.076445,0.058613
1,(Roll-On),(After Shave Losyon),0.028689,0.003981,0.000410,0.014286,3.588165,1.0,0.000296,1.010454,0.742611,0.012704,0.010346,0.058613
2,(Tıraş Jeli),(After Shave Losyon),0.003981,0.003981,0.000390,0.098039,24.624664,1.0,0.000374,1.104282,0.963225,0.051546,0.094434,0.098039
3,(After Shave Losyon),(Tıraş Jeli),0.003981,0.003981,0.000390,0.098039,24.624664,1.0,0.000374,1.104282,0.963225,0.051546,0.094434,0.098039
4,(Peeling),(Akne Bakım),0.007338,0.002635,0.000449,0.061170,23.217041,1.0,0.000430,1.062349,0.964002,0.047131,0.058690,0.115770
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1960,"(Saç Kremi, Saç Maskesi)","(Şampuan, Saç Spreyi)",0.004137,0.002830,0.000468,0.113208,40.004424,1.0,0.000457,1.124468,0.979054,0.072072,0.110691,0.139362
1961,"(Şampuan, Saç Maskesi)","(Saç Kremi, Saç Spreyi)",0.004801,0.002147,0.000468,0.097561,45.444789,1.0,0.000458,1.105729,0.982713,0.072289,0.095619,0.157871
1962,(Saç Spreyi),"(Saç Kremi, Şampuan, Saç Maskesi)",0.010949,0.002830,0.000468,0.042781,15.117536,1.0,0.000437,1.041736,0.944189,0.035191,0.040064,0.104149
1963,(Saç Kremi),"(Şampuan, Saç Maskesi, Saç Spreyi)",0.036418,0.000546,0.000468,0.012862,23.536518,1.0,0.000448,1.012476,0.993701,0.012834,0.012322,0.435002
1964,(Saç Maskesi),"(Saç Kremi, Şampuan, Saç Spreyi)",0.011241,0.001561,0.000468,0.041667,26.686979,1.0,0.000451,1.041849,0.973472,0.037975,0.040168,0.170833